using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using TMPro;
using System.Collections.Generic;
using UnityEngine.UIElements;
using System.ComponentModel.Design;
using Unity.VisualScripting;

public class WaveSystem : MonoBehaviour , IEventListener
{
    private int currentWave = 0;
    public float waveValue = 5;

    public float waveMultiplier =1.2f; 

    public static bool gainFullHealthOnEnd = false;
    public static int skillPointsOnEnd = 0;

    

    private float spawnTimer;

    private int enemiesLeft;


    public List<Enemy> enemylist = new List<Enemy>();

    public List<GameObject> spawnLocation = new List<GameObject>();

    private List<GameObject> enemiesToSpawn = new List<GameObject>();

    public TextMeshProUGUI currentWaveUIText;


    private int minValue;
    public GameObject hei_boss;
    public GameObject bai_boss;
    public bool spawnBoss = true;



    // Start is called once before the first execution of Update after the MonoBehaviour is created
    private void Start(){
        minValue = GetMinValue();
        subscribe();
        GenerateWave();
       
    
    }

    // Update is called once per frame
    private void Update()
    {
       //Debug.Log("how many enemy: " + enemiesLeft);
       //Debug.Log("current Wave"+currentWave);
        
        
    }

    private int GetMinValue(){
        int min = 10000;
        for(int i=0; i< enemylist.Count;i++){
            if(enemylist[i].value<min) min = enemylist[i].value;
        }
        return min;
    }

    public void GenerateWave(){
        if(currentWave == 3 && spawnBoss){
            Debug.Log("you spawn heibai");
            hei_boss.SetActive(true);
            bai_boss.SetActive(true);
            spawnBoss = false;
        }

        //Debug.Log("generate wave current number enemies"+enemiesLeft);
        GenerateEnemies();
        enemiesLeft = enemiesToSpawn.Count;
        if(enemiesLeft == 0) return;
        StartCoroutine(SpawnEnemies());
        waveValue = waveValue + currentWave*waveMultiplier;
        waveValue*= waveMultiplier;
        currentWave++;
        currentWaveUIText.text = "Wave: " + currentWave;
    }

    
    
    /// <summary>
    /// Spawn enemies that were generated by the generateEnemies() function
    /// </summary>
    public IEnumerator SpawnEnemies(){
        
        List<GameObject> list = new List<GameObject>(enemiesToSpawn); 
        while(list.Count> 0 ){
            int randomSpawnPoint = Random.Range(0, spawnLocation.Count);
            GameObject enemy = Instantiate(enemiesToSpawn[0], spawnLocation[randomSpawnPoint].transform.position, Quaternion.identity);
           
            list.RemoveAt(0);
            yield return new WaitForSeconds(1);
        }
        
    }


    private void EnemyDied()
    {
        enemiesLeft--;
        //Debug.Log("enemies left to kill : " + enemiesLeft);
        //currentWaveUIText.text = "enemies left to kill : " + enemiesLeft + " Wave: " + currentWave;
        if (enemiesLeft <= 0)
        {
            OnWaveComplete();
        }
    }
    public void GenerateEnemies(){
        Debug.Log("Generating Enemies...");
        int valueToSpend = (int)waveValue;
        List<GameObject> generatedEnemies = new List<GameObject>();
        while(valueToSpend>0){
            //Debug.Log("you should add an enemy");
            int randomEnemy = Random.Range(0,enemylist.Count);
            if(valueToSpend-enemylist[randomEnemy].value>=0){
                generatedEnemies.Add(enemylist[randomEnemy].enemyPrefab);
                valueToSpend-=enemylist[randomEnemy].value;//randomEnemy;
                //Debug.Log("Added enemy: " + enemylist[randomEnemy].enemyPrefab.name + ", Remaining Value: " + valueToSpend);
            }
            else if(valueToSpend < minValue) break;
        }
        enemiesToSpawn.Clear();
        enemiesToSpawn = generatedEnemies;
        //Debug.Log("Enemies generated: " + enemiesToSpawn.Count);
    }

    public void OnWaveComplete(){
        if(gainFullHealthOnEnd) EventManager.PlayerTakeDamage(-1000);
        if(skillPointsOnEnd !=0) EventManager.SkillPointAcquired(skillPointsOnEnd);
        GenerateWave();

    }


    public void subscribe()
    {
        EventManager.OnEnemyDied += EnemyDied;
    }

    public void unsubscribe()
    {
        EventManager.OnEnemyDied -= EnemyDied;
    }
    public void OnDisable(){
        unsubscribe();
    }
}
[System.Serializable]
public class Enemy{
    public GameObject enemyPrefab;
    public int value;
    }
