using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using TMPro;
using System.Collections.Generic;
using System.ComponentModel.Design;
using Unity.VisualScripting;

public class WaveSystem : MonoBehaviour , IEventListener
{
    private int currentWave = 0;
    public float waveValue = 5;

    public float waveMultiplier =1.2f; 

    public static bool gainFullHealthOnEnd = false;
    public static int skillPointsOnEnd = 0;

    public int timeBetweenWave = 5;

    private float spawnTimer;

    private int enemiesLeft;


    public List<Enemy> enemylist = new List<Enemy>();

    public List<GameObject> spawnLocation = new List<GameObject>();

    

    public TextMeshProUGUI currentWaveUIText;
    public TextMeshProUGUI waveCompleteUIText;

    private TextMeshProUGUI waveBeginCountdown;
    private TextMeshProUGUI waveHint;

    public GameObject SkillTreeButtonComponent;
    private TextMeshProUGUI skillTreeText;
    private Button skillTreeButton;

    private int minValue;
    public GameObject hei_boss;
    public GameObject bai_boss;
    public bool spawnBoss = true;



    // Start is called once before the first execution of Update after the MonoBehaviour is created
    private void Start(){
        minValue = GetMinValue();
        subscribe();
        GenerateWave();
        
        waveBeginCountdown = waveCompleteUIText.transform.Find("Countdown").GetComponent<TextMeshProUGUI>();
        waveHint = waveCompleteUIText.transform.Find("Hint").GetComponent<TextMeshProUGUI>();
        
        SetTextAlpha(waveHint, 0f);
        SetTextAlpha(waveBeginCountdown, 0f);
        SetTextAlpha(waveCompleteUIText, 0f);
        
        skillTreeButton = SkillTreeButtonComponent.GetComponent<Button>();
        skillTreeButton.interactable = false;
        skillTreeText = SkillTreeButtonComponent.GetComponentInChildren<TextMeshProUGUI>(true);
        SetTextAlpha(skillTreeText,0.5f);
    
    }
    private void SetTextAlpha(TextMeshProUGUI textElement, float alpha){
        if (textElement != null){
            Color color = textElement.color;
            color.a = alpha;
            textElement.color = color;
        }
    }

    // Update is called once per frame
    private void Update()
    {
       //Debug.Log("how many enemy: " + enemiesLeft);
       //Debug.Log("current Wave"+currentWave);
        
        
    }

    private int GetMinValue(){
        int min = 10000;
        for(int i=0; i< enemylist.Count;i++){
            if(enemylist[i].value<min) min = enemylist[i].value;
        }
        return min;
    }

    public void GenerateWave(){
        if(currentWave == 3 && spawnBoss){
            Debug.Log("you spawn heibai");
            hei_boss.SetActive(true);
            bai_boss.SetActive(true);
            spawnBoss = false;
        }

        List<GameObject> enemiesToSpawn = GenerateEnemies();
        enemiesLeft = enemiesToSpawn.Count;
        Debug.Log("generate wave current number enemies"+enemiesLeft);
        
        if(enemiesLeft == 0) return;
        
        StartCoroutine(SpawnEnemies(enemiesToSpawn));
        //waveValue = waveValue + currentWave*waveMultiplier;
        waveValue*= waveMultiplier;
        currentWave++;
        currentWaveUIText.text = "Wave: " + currentWave;
    }

    
    
    /// <summary>
    /// Spawn enemies that were generated by the generateEnemies() function
    /// </summary>
    public IEnumerator SpawnEnemies(List<GameObject> spawnEnemies){
        
        List<GameObject> list = new List<GameObject>(spawnEnemies); 
        while(list.Count> 0 ){
            int randomSpawnPoint = Random.Range(0, spawnLocation.Count);
            GameObject enemy = Instantiate(list[0], spawnLocation[randomSpawnPoint].transform.position, Quaternion.identity);
           
            list.RemoveAt(0);
            yield return new WaitForSeconds(1);
        }
        
    }


    private void EnemyDied()
    {
        enemiesLeft--;
        //Debug.Log("enemies left to kill : " + enemiesLeft);
        //currentWaveUIText.text = "enemies left to kill : " + enemiesLeft + " Wave: " + currentWave;
        if (enemiesLeft <= 0)
        {
            StartCoroutine(OnWaveComplete());
        }
    }
    public List<GameObject> GenerateEnemies(){
        //Debug.Log("Generating Enemies...");

        List<GameObject> generatedEnemies = new List<GameObject>();
        int valueToSpend = (int)waveValue;
        
        
        while(valueToSpend>0){
            int selectedEnemy = Random.Range(0,enemylist.Count);
            
            if(valueToSpend- enemylist[selectedEnemy].value >= 0){
                generatedEnemies.Add(enemylist[selectedEnemy].enemyPrefab);
                valueToSpend-=enemylist[selectedEnemy].value;
            }
            
            if(valueToSpend < minValue) break;
        }

        return generatedEnemies;
        //Debug.Log("Enemies generated: " + enemiesToSpawn.Count);
    }

    private IEnumerator OnWaveComplete(){
        if(gainFullHealthOnEnd) EventManager.PlayerTakeDamage(-1000);
        if(skillPointsOnEnd !=0) EventManager.SkillPointAcquired(skillPointsOnEnd);
        
        
        
        yield return StartCoroutine(FadeText(0f, 1f, 1f));
        
        skillTreeButton.interactable = true;
        SetTextAlpha(skillTreeText,1f);
        
        for(int i=timeBetweenWave; i>0;i--){
            waveBeginCountdown.text = "Next wave starting in: "+i;
            yield return new WaitForSeconds(1);
        } 
        StartCoroutine(FadeText(1f, 0f, 1f)); 
        
        skillTreeButton.interactable = false;
        SetTextAlpha(skillTreeText,0.5f);
        
        GenerateWave();
        AudioManager.instance.PlaySound("WaveStart");
        yield return StartCoroutine(FadeText(1f, 0f, 1f));
    
    }
    


    public void subscribe()
    {
        EventManager.OnEnemyDied += EnemyDied;
    }

    public void unsubscribe()
    {
        EventManager.OnEnemyDied -= EnemyDied;
    }
    public void OnDisable(){
        unsubscribe();
    }
    
    
    
    
    private IEnumerator FadeText(float startAlpha, float endAlpha, float duration){
        float elapsedTime = 0f;
        Color color = waveCompleteUIText.color;

        while (elapsedTime < duration){
            elapsedTime += Time.deltaTime;
            color.a = Mathf.Lerp(startAlpha, endAlpha, elapsedTime / duration);
            
            waveCompleteUIText.color = color;
            waveHint.color = color;
            waveBeginCountdown.color = color;
            
            yield return null;
        }

        color.a = endAlpha;
        waveCompleteUIText.color = color;
        }
    }


[System.Serializable]
public class Enemy{
    public GameObject enemyPrefab;
    public int value;
    }
